[package]
name = "launchpad-common"
version = "0.0.0"
authors = [ "Dorin Marian Iancu <dorin.iancu@dharitri.com>",]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "0.12.1"

[dependencies.dharitri-sc-modules]
version = "0.12.1"
